export { default as ClientController } from "./client.controller";
export { default as DueController } from "./due.controller";
export { default as PaymentsController } from "./payments.controller";
export { default as ProductController } from "./product.controller";
export { default as PatientController } from "./patient.controller"
export { default as MedicalController } from "./medical.controller";
export { default as ConsultingController } from "./consulting.controller";
export { default as QueueController } from "./queue.controller";
export { default as FeeController } from "./fee.controller";
export { default as UsersController } from '@/core/controller/users.controller'
export { default as NodemailerController } from '@/core/controller/nodemailer.controller'
export { default as EventsController } from '@/core/controller/events.controller';
